### SEND FETCH SONGS REQUEST
GET {{baseUrl}}/songs?page=1&limit=20
#GET {{baseUrl}}/songs?page=1&limit=2&order=DESC&sortBy=title
Authorization: Bearer {{authToken}}


### Find SONGS REQUEST
GET {{baseUrl}}/songs/14
Authorization: Bearer {{authToken}}


### Create New SONGS REQUEST
POST {{baseUrl}}/songs
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "You for Me 12",
  "artists": [
    1
  ],
  "releasedDate": "2022-09-30",
  "duration": "02:45",
  "lyrics": "Sby, you're my adrenaline. Brought out this other side of me Youdon't even know Controlling my whole anatomy, oh Fingers are holding you right atthe edge You're slipping out of my hands Keeping my secrets all up in my head I'mscared that you won't want me back, oh I dance to every song like it's about ya Idrink 'til I kiss someone who looks like ya I wish that I was honest when I had youI shoulda told you that I wanted you for me I dance to every song like it's aboutya I drink 'til I kiss someone who looks like ya"
}


### Update SONGS REQUEST
PUT {{baseUrl}}/songs/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "You for Me 222",
  "artists": [
    "Siagla",
    "Yan"
  ],
  "releasedDate": "2022-09-30",
  "duration": "02:45",
  "lyrics": "Sby, you're my adrenaline. Brought out this other side of me Youdon't even know Controlling my whole anatomy, oh Fingers are holding you right atthe edge You're slipping out of my hands Keeping my secrets all up in my head I'mscared that you won't want me back, oh I dance to every song like it's about ya Idrink 'til I kiss someone who looks like ya I wish that I was honest when I had youI shoulda told you that I wanted you for me I dance to every song like it's aboutya I drink 'til I kiss someone who looks like ya"
}

### DELETE SONGS REQUEST
DELETE {{baseUrl}}/songs/5
Authorization: Bearer {{authToken}}

